export const mermaidThemeDirectives = {
  themeVariables: {
    // fontFamily: 'Red Hat Mono',
    // fontSize: '12',
    background: '#1d2433',
    primaryColor: '#212e3f',
    secondaryColor: '#192330',
    tertiaryColor: '#131a24',
    // primaryTextColor: "#d7dce2",
    // secondaryTextColor: "#d7dce2",
    // tertiaryTextColor: "#d7dce2",
    primaryBorderColor: '',
    secondaryBorderColor: '',
    tertiaryBorderColor: '',
    // noteBkgColor: "",
    // noteTextColor: "",
    // noteBorderColor: "",
    lineColor: '#bae67e99',
    // textColor: "",
    // mainBkg: "",
    // errorBkgColor: "",
    // errorTextColor: "",
  },
}
